#!/bin/bash

var=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep  "percentage")
size=${#var} 
status=${var:(size-3):2}

if [ "$status" -lt 30 ]
  then
    zenity --warning --text "Your energy is getting low!\n$var" --title "Low energy" --display=:0.0
fi

